-- merged from V18__seed_grafxkid_avatar_shop_items.sql
UPDATE item
SET status = 'INACTIVE',
    updated_at = NOW()
WHERE category = 'AVATAR'
  AND name = 'Basic MiniMe';

INSERT INTO item (
    category,
    name,
    description,
    price,
    status,
    sales_count,
    creator_id,
    asset_key,
    asset_url,
    asset_width,
    asset_height,
    placement_type,
    created_at,
    updated_at
)
SELECT
    'AVATAR',
    seed.name,
    seed.description,
    seed.price,
    'ACTIVE',
    0,
    u.user_id,
    seed.asset_key,
    seed.asset_url,
    36,
    56,
    'FLOOR',
    NOW(),
    NOW()
FROM users u
CROSS JOIN (
    VALUES
        ('그래픽키드 아바타 01', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_01', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_01.png'),
        ('그래픽키드 아바타 02', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_02', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_02.png'),
        ('그래픽키드 아바타 03', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_03', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_03.png'),
        ('그래픽키드 아바타 04', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_04', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_04.png'),
        ('그래픽키드 아바타 05', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_05', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_05.png'),
        ('그래픽키드 아바타 06', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_06', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_06.png'),
        ('그래픽키드 아바타 07', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_07', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_07.png'),
        ('그래픽키드 아바타 08', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_08', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_08.png'),
        ('그래픽키드 아바타 09', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_09', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_09.png'),
        ('그래픽키드 아바타 10', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_10', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_10.png'),
        ('그래픽키드 아바타 11', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_11', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_11.png'),
        ('그래픽키드 아바타 12', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_12', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_12.png'),
        ('그래픽키드 아바타 13', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_13', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_13.png'),
        ('그래픽키드 아바타 14', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_14', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_14.png'),
        ('그래픽키드 아바타 15', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_15', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_15.png'),
        ('그래픽키드 아바타 16', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_16', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_16.png'),
        ('그래픽키드 아바타 17', '구매 가능한 픽셀 아바타', 700, 'grafxkid_avatar_17', '/miniroom-assets/avatars-grafxkid/grafxkid_avatar_17.png')
) AS seed(name, description, price, asset_key, asset_url)
WHERE u.email = 'miniroom-dev@example.com'
  AND NOT EXISTS (
      SELECT 1
      FROM item i
      WHERE i.asset_key = seed.asset_key
  );


-- merged from V20__seed_kenney_isometric_shop_items.sql
INSERT INTO item (
    category,
    name,
    description,
    price,
    status,
    sales_count,
    creator_id,
    asset_key,
    asset_url,
    asset_width,
    asset_height,
    placement_type,
    created_at,
    updated_at
)
SELECT
    'MINIROOM',
    seed.name,
    seed.description,
    seed.price,
    'ACTIVE',
    0,
    u.user_id,
    seed.asset_key,
    seed.asset_url,
    seed.asset_width,
    seed.asset_height,
    'FLOOR',
    NOW(),
    NOW()
FROM users u
CROSS JOIN (
    VALUES
        ('Kenney Bathroom Cabinet', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bathroom_cabinet_se', '/miniroom-assets/kenney/isometric/bathroomCabinet_SE.png', 28, 49),
        ('Kenney Bathroom Mirror', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bathroom_mirror_se', '/miniroom-assets/kenney/isometric/bathroomMirror_SE.png', 34, 53),
        ('Kenney Bathroom Sink', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bathroom_sink_se', '/miniroom-assets/kenney/isometric/bathroomSink_SE.png', 43, 59),
        ('Kenney Bathtub', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bathtub_se', '/miniroom-assets/kenney/isometric/bathtub_SE.png', 130, 118),
        ('Kenney Bear', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bear_se', '/miniroom-assets/kenney/isometric/bear_SE.png', 38, 39),
        ('Kenney Bed Bunk', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bed_bunk_se', '/miniroom-assets/kenney/isometric/bedBunk_SE.png', 125, 153),
        ('Kenney Bed Double', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bed_double_se', '/miniroom-assets/kenney/isometric/bedDouble_SE.png', 157, 138),
        ('Kenney Bed Single', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bed_single_se', '/miniroom-assets/kenney/isometric/bedSingle_SE.png', 128, 118),
        ('Kenney Bench', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bench_se', '/miniroom-assets/kenney/isometric/bench_SE.png', 46, 67),
        ('Kenney Bench Cushion', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bench_cushion_se', '/miniroom-assets/kenney/isometric/benchCushion_SE.png', 46, 67),
        ('Kenney Bench Cushion Low', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bench_cushion_low_se', '/miniroom-assets/kenney/isometric/benchCushionLow_SE.png', 49, 48),
        ('Kenney Bookcase Closed', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bookcase_closed_se', '/miniroom-assets/kenney/isometric/bookcaseClosed_SE.png', 50, 99),
        ('Kenney Bookcase Closed Doors', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bookcase_closed_doors_se', '/miniroom-assets/kenney/isometric/bookcaseClosedDoors_SE.png', 50, 99),
        ('Kenney Bookcase Closed Wide', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bookcase_closed_wide_se', '/miniroom-assets/kenney/isometric/bookcaseClosedWide_SE.png', 80, 115),
        ('Kenney Bookcase Open', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bookcase_open_se', '/miniroom-assets/kenney/isometric/bookcaseOpen_SE.png', 50, 101),
        ('Kenney Bookcase Open Low', 'Kenney isometric miniroom item', 400, 'kenney_isometric_bookcase_open_low_se', '/miniroom-assets/kenney/isometric/bookcaseOpenLow_SE.png', 50, 65),
        ('Kenney Books', 'Kenney isometric miniroom item', 400, 'kenney_isometric_books_se', '/miniroom-assets/kenney/isometric/books_SE.png', 19, 19),
        ('Kenney Cabinet Bed', 'Kenney isometric miniroom item', 400, 'kenney_isometric_cabinet_bed_se', '/miniroom-assets/kenney/isometric/cabinetBed_SE.png', 37, 42),
        ('Kenney Cabinet Bed Drawer', 'Kenney isometric miniroom item', 400, 'kenney_isometric_cabinet_bed_drawer_se', '/miniroom-assets/kenney/isometric/cabinetBedDrawer_SE.png', 37, 44),
        ('Kenney Cabinet Bed Drawer Table', 'Kenney isometric miniroom item', 400, 'kenney_isometric_cabinet_bed_drawer_table_se', '/miniroom-assets/kenney/isometric/cabinetBedDrawerTable_SE.png', 37, 44),
        ('Kenney Cabinet Television', 'Kenney isometric miniroom item', 400, 'kenney_isometric_cabinet_television_se', '/miniroom-assets/kenney/isometric/cabinetTelevision_SE.png', 80, 79),
        ('Kenney Cabinet Television Doors', 'Kenney isometric miniroom item', 400, 'kenney_isometric_cabinet_television_doors_se', '/miniroom-assets/kenney/isometric/cabinetTelevisionDoors_SE.png', 80, 79),
        ('Kenney Cardboard Box Closed', 'Kenney isometric miniroom item', 400, 'kenney_isometric_cardboard_box_closed_se', '/miniroom-assets/kenney/isometric/cardboardBoxClosed_SE.png', 32, 39),
        ('Kenney Cardboard Box Open', 'Kenney isometric miniroom item', 400, 'kenney_isometric_cardboard_box_open_se', '/miniroom-assets/kenney/isometric/cardboardBoxOpen_SE.png', 44, 48),
        ('Kenney Ceiling Fan', 'Kenney isometric miniroom item', 400, 'kenney_isometric_ceiling_fan_se', '/miniroom-assets/kenney/isometric/ceilingFan_SE.png', 54, 40),
        ('Kenney Chair', 'Kenney isometric miniroom item', 400, 'kenney_isometric_chair_se', '/miniroom-assets/kenney/isometric/chair_SE.png', 31, 57),
        ('Kenney Chair Cushion', 'Kenney isometric miniroom item', 400, 'kenney_isometric_chair_cushion_se', '/miniroom-assets/kenney/isometric/chairCushion_SE.png', 31, 56),
        ('Kenney Chair Desk', 'Kenney isometric miniroom item', 400, 'kenney_isometric_chair_desk_se', '/miniroom-assets/kenney/isometric/chairDesk_SE.png', 44, 71),
        ('Kenney Chair Rounded', 'Kenney isometric miniroom item', 400, 'kenney_isometric_chair_rounded_se', '/miniroom-assets/kenney/isometric/chairRounded_SE.png', 31, 52),
        ('Kenney Coat Rack', 'Kenney isometric miniroom item', 400, 'kenney_isometric_coat_rack_se', '/miniroom-assets/kenney/isometric/coatRack_SE.png', 44, 46),
        ('Kenney Coat Rack Standing', 'Kenney isometric miniroom item', 400, 'kenney_isometric_coat_rack_standing_se', '/miniroom-assets/kenney/isometric/coatRackStanding_SE.png', 24, 73),
        ('Kenney Computer Keyboard', 'Kenney isometric miniroom item', 400, 'kenney_isometric_computer_keyboard_se', '/miniroom-assets/kenney/isometric/computerKeyboard_SE.png', 31, 23),
        ('Kenney Computer Mouse', 'Kenney isometric miniroom item', 400, 'kenney_isometric_computer_mouse_se', '/miniroom-assets/kenney/isometric/computerMouse_SE.png', 8, 8),
        ('Kenney Computer Screen', 'Kenney isometric miniroom item', 400, 'kenney_isometric_computer_screen_se', '/miniroom-assets/kenney/isometric/computerScreen_SE.png', 35, 43),
        ('Kenney Desk', 'Kenney isometric miniroom item', 400, 'kenney_isometric_desk_se', '/miniroom-assets/kenney/isometric/desk_SE.png', 85, 88),
        ('Kenney Desk Corner', 'Kenney isometric miniroom item', 400, 'kenney_isometric_desk_corner_se', '/miniroom-assets/kenney/isometric/deskCorner_SE.png', 147, 101),
        ('Kenney Doorway', 'Kenney isometric miniroom item', 400, 'kenney_isometric_doorway_se', '/miniroom-assets/kenney/isometric/doorway_SE.png', 44, 107),
        ('Kenney Doorway Front', 'Kenney isometric miniroom item', 400, 'kenney_isometric_doorway_front_se', '/miniroom-assets/kenney/isometric/doorwayFront_SE.png', 44, 107),
        ('Kenney Doorway Open', 'Kenney isometric miniroom item', 400, 'kenney_isometric_doorway_open_se', '/miniroom-assets/kenney/isometric/doorwayOpen_SE.png', 44, 107),
        ('Kenney Dryer', 'Kenney isometric miniroom item', 400, 'kenney_isometric_dryer_se', '/miniroom-assets/kenney/isometric/dryer_SE.png', 56, 74),
        ('Kenney Floor Corner', 'Kenney isometric miniroom item', 400, 'kenney_isometric_floor_corner_se', '/miniroom-assets/kenney/isometric/floorCorner_SE.png', 75, 62),
        ('Kenney Floor Corner Round', 'Kenney isometric miniroom item', 400, 'kenney_isometric_floor_corner_round_se', '/miniroom-assets/kenney/isometric/floorCornerRound_SE.png', 79, 62),
        ('Kenney Floor Full', 'Kenney isometric miniroom item', 400, 'kenney_isometric_floor_full_se', '/miniroom-assets/kenney/isometric/floorFull_SE.png', 151, 110),
        ('Kenney Floor Half', 'Kenney isometric miniroom item', 400, 'kenney_isometric_floor_half_se', '/miniroom-assets/kenney/isometric/floorHalf_SE.png', 113, 84),
        ('Kenney Kitchen Bar', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_bar_se', '/miniroom-assets/kenney/isometric/kitchenBar_SE.png', 49, 64),
        ('Kenney Kitchen Bar End', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_bar_end_se', '/miniroom-assets/kenney/isometric/kitchenBarEnd_SE.png', 19, 42),
        ('Kenney Kitchen Blender', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_blender_se', '/miniroom-assets/kenney/isometric/kitchenBlender_SE.png', 12, 24),
        ('Kenney Kitchen Cabinet', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_cabinet_se', '/miniroom-assets/kenney/isometric/kitchenCabinet_SE.png', 67, 79),
        ('Kenney Kitchen Cabinet Corner Inner', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_cabinet_corner_inner_se', '/miniroom-assets/kenney/isometric/kitchenCabinetCornerInner_SE.png', 70, 81),
        ('Kenney Kitchen Cabinet Corner Round', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_cabinet_corner_round_se', '/miniroom-assets/kenney/isometric/kitchenCabinetCornerRound_SE.png', 68, 69),
        ('Kenney Kitchen Cabinet Drawer 1', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_cabinet_drawer_1_se', '/miniroom-assets/kenney/isometric/kitchenCabinetDrawer 1_SE.png', 67, 79),
        ('Kenney Kitchen Cabinet Drawer', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_cabinet_drawer_se', '/miniroom-assets/kenney/isometric/kitchenCabinetDrawer_SE.png', 56, 70),
        ('Kenney Kitchen Cabinet Upper', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_cabinet_upper_se', '/miniroom-assets/kenney/isometric/kitchenCabinetUpper_SE.png', 49, 64),
        ('Kenney Kitchen Cabinet Upper Corner', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_cabinet_upper_corner_se', '/miniroom-assets/kenney/isometric/kitchenCabinetUpperCorner_SE.png', 33, 50),
        ('Kenney Kitchen Cabinet Upper Double', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_cabinet_upper_double_se', '/miniroom-assets/kenney/isometric/kitchenCabinetUpperDouble_SE.png', 49, 64),
        ('Kenney Kitchen Cabinet Upper Low', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_cabinet_upper_low_se', '/miniroom-assets/kenney/isometric/kitchenCabinetUpperLow_SE.png', 49, 49),
        ('Kenney Kitchen Coffee Machine', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_coffee_machine_se', '/miniroom-assets/kenney/isometric/kitchenCoffeeMachine_SE.png', 26, 32),
        ('Kenney Kitchen Fridge', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_fridge_se', '/miniroom-assets/kenney/isometric/kitchenFridge_SE.png', 52, 105),
        ('Kenney Kitchen Fridge Built In', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_fridge_built_in_se', '/miniroom-assets/kenney/isometric/kitchenFridgeBuiltIn_SE.png', 65, 110),
        ('Kenney Kitchen Fridge Small', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_fridge_small_se', '/miniroom-assets/kenney/isometric/kitchenFridgeSmall_SE.png', 52, 81),
        ('Kenney Kitchen Microwave', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_microwave_se', '/miniroom-assets/kenney/isometric/kitchenMicrowave_SE.png', 37, 40),
        ('Kenney Kitchen Sink', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_sink_se', '/miniroom-assets/kenney/isometric/kitchenSink_SE.png', 67, 79),
        ('Kenney Kitchen Stove', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_stove_se', '/miniroom-assets/kenney/isometric/kitchenStove_SE.png', 67, 79),
        ('Kenney Kitchen Stove Electric', 'Kenney isometric miniroom item', 400, 'kenney_isometric_kitchen_stove_electric_se', '/miniroom-assets/kenney/isometric/kitchenStoveElectric_SE.png', 67, 79),
        ('Kenney Lamp Round Floor', 'Kenney isometric miniroom item', 400, 'kenney_isometric_lamp_round_floor_se', '/miniroom-assets/kenney/isometric/lampRoundFloor_SE.png', 19, 76),
        ('Kenney Lamp Round Table', 'Kenney isometric miniroom item', 400, 'kenney_isometric_lamp_round_table_se', '/miniroom-assets/kenney/isometric/lampRoundTable_SE.png', 19, 35),
        ('Kenney Lamp Square Ceiling', 'Kenney isometric miniroom item', 400, 'kenney_isometric_lamp_square_ceiling_se', '/miniroom-assets/kenney/isometric/lampSquareCeiling_SE.png', 19, 28),
        ('Kenney Lamp Square Floor', 'Kenney isometric miniroom item', 400, 'kenney_isometric_lamp_square_floor_se', '/miniroom-assets/kenney/isometric/lampSquareFloor_SE.png', 19, 78),
        ('Kenney Lamp Square Table', 'Kenney isometric miniroom item', 400, 'kenney_isometric_lamp_square_table_se', '/miniroom-assets/kenney/isometric/lampSquareTable_SE.png', 19, 35),
        ('Kenney Laptop', 'Kenney isometric miniroom item', 400, 'kenney_isometric_laptop_se', '/miniroom-assets/kenney/isometric/laptop_SE.png', 38, 38),
        ('Kenney Lounge Chair', 'Kenney isometric miniroom item', 400, 'kenney_isometric_lounge_chair_se', '/miniroom-assets/kenney/isometric/loungeChair_SE.png', 67, 77),
        ('Kenney Lounge Chair Relax', 'Kenney isometric miniroom item', 400, 'kenney_isometric_lounge_chair_relax_se', '/miniroom-assets/kenney/isometric/loungeChairRelax_SE.png', 78, 97),
        ('Kenney Lounge Sofa', 'Kenney isometric miniroom item', 400, 'kenney_isometric_lounge_sofa_se', '/miniroom-assets/kenney/isometric/loungeSofa_SE.png', 104, 103),
        ('Kenney Lounge Sofa Corner', 'Kenney isometric miniroom item', 400, 'kenney_isometric_lounge_sofa_corner_se', '/miniroom-assets/kenney/isometric/loungeSofaCorner_SE.png', 148, 108),
        ('Kenney Lounge Sofa Long', 'Kenney isometric miniroom item', 400, 'kenney_isometric_lounge_sofa_long_se', '/miniroom-assets/kenney/isometric/loungeSofaLong_SE.png', 131, 103),
        ('Kenney Lounge Sofa Ottoman', 'Kenney isometric miniroom item', 400, 'kenney_isometric_lounge_sofa_ottoman_se', '/miniroom-assets/kenney/isometric/loungeSofaOttoman_SE.png', 68, 63),
        ('Kenney Paneling', 'Kenney isometric miniroom item', 400, 'kenney_isometric_paneling_se', '/miniroom-assets/kenney/isometric/paneling_SE.png', 40, 73),
        ('Kenney Pillow', 'Kenney isometric miniroom item', 400, 'kenney_isometric_pillow_se', '/miniroom-assets/kenney/isometric/pillow_SE.png', 21, 29),
        ('Kenney Pillow Long', 'Kenney isometric miniroom item', 400, 'kenney_isometric_pillow_long_se', '/miniroom-assets/kenney/isometric/pillowLong_SE.png', 33, 38),
        ('Kenney Plant Small1', 'Kenney isometric miniroom item', 400, 'kenney_isometric_plant_small1_se', '/miniroom-assets/kenney/isometric/plantSmall1_SE.png', 11, 14),
        ('Kenney Plant Small2', 'Kenney isometric miniroom item', 400, 'kenney_isometric_plant_small2_se', '/miniroom-assets/kenney/isometric/plantSmall2_SE.png', 11, 14),
        ('Kenney Plant Small3', 'Kenney isometric miniroom item', 400, 'kenney_isometric_plant_small3_se', '/miniroom-assets/kenney/isometric/plantSmall3_SE.png', 10, 15),
        ('Kenney Potted Plant', 'Kenney isometric miniroom item', 400, 'kenney_isometric_potted_plant_se', '/miniroom-assets/kenney/isometric/pottedPlant_SE.png', 21, 60),
        ('Kenney Radio', 'Kenney isometric miniroom item', 400, 'kenney_isometric_radio_se', '/miniroom-assets/kenney/isometric/radio_SE.png', 31, 36),
        ('Kenney Rug Rectangle', 'Kenney isometric miniroom item', 400, 'kenney_isometric_rug_rectangle_se', '/miniroom-assets/kenney/isometric/rugRectangle_SE.png', 188, 134),
        ('Kenney Rug Round', 'Kenney isometric miniroom item', 400, 'kenney_isometric_rug_round_se', '/miniroom-assets/kenney/isometric/rugRound_SE.png', 99, 71),
        ('Kenney Rug Rounded', 'Kenney isometric miniroom item', 400, 'kenney_isometric_rug_rounded_se', '/miniroom-assets/kenney/isometric/rugRounded_SE.png', 148, 105),
        ('Kenney Rug Square', 'Kenney isometric miniroom item', 400, 'kenney_isometric_rug_square_se', '/miniroom-assets/kenney/isometric/rugSquare_SE.png', 138, 98),
        ('Kenney Shower', 'Kenney isometric miniroom item', 400, 'kenney_isometric_shower_se', '/miniroom-assets/kenney/isometric/shower_SE.png', 85, 142),
        ('Kenney Side Table', 'Kenney isometric miniroom item', 400, 'kenney_isometric_side_table_se', '/miniroom-assets/kenney/isometric/sideTable_SE.png', 58, 68),
        ('Kenney Side Table Drawers', 'Kenney isometric miniroom item', 400, 'kenney_isometric_side_table_drawers_se', '/miniroom-assets/kenney/isometric/sideTableDrawers_SE.png', 58, 68),
        ('Kenney Speaker', 'Kenney isometric miniroom item', 400, 'kenney_isometric_speaker_se', '/miniroom-assets/kenney/isometric/speaker_SE.png', 23, 64),
        ('Kenney Speaker Small', 'Kenney isometric miniroom item', 400, 'kenney_isometric_speaker_small_se', '/miniroom-assets/kenney/isometric/speakerSmall_SE.png', 22, 37),
        ('Kenney Stool Bar', 'Kenney isometric miniroom item', 400, 'kenney_isometric_stool_bar_se', '/miniroom-assets/kenney/isometric/stoolBar_SE.png', 27, 49),
        ('Kenney Stool Bar Square', 'Kenney isometric miniroom item', 400, 'kenney_isometric_stool_bar_square_se', '/miniroom-assets/kenney/isometric/stoolBarSquare_SE.png', 23, 46),
        ('Kenney Table', 'Kenney isometric miniroom item', 400, 'kenney_isometric_table_se', '/miniroom-assets/kenney/isometric/table_SE.png', 98, 93),
        ('Kenney Table Cloth', 'Kenney isometric miniroom item', 400, 'kenney_isometric_table_cloth_se', '/miniroom-assets/kenney/isometric/tableCloth_SE.png', 98, 93),
        ('Kenney Table Coffee', 'Kenney isometric miniroom item', 400, 'kenney_isometric_table_coffee_se', '/miniroom-assets/kenney/isometric/tableCoffee_SE.png', 80, 74),
        ('Kenney Table Coffee Glass', 'Kenney isometric miniroom item', 400, 'kenney_isometric_table_coffee_glass_se', '/miniroom-assets/kenney/isometric/tableCoffeeGlass_SE.png', 80, 74),
        ('Kenney Table Coffee Glass Square', 'Kenney isometric miniroom item', 400, 'kenney_isometric_table_coffee_glass_square_se', '/miniroom-assets/kenney/isometric/tableCoffeeGlassSquare_SE.png', 60, 60),
        ('Kenney Table Coffee Square', 'Kenney isometric miniroom item', 400, 'kenney_isometric_table_coffee_square_se', '/miniroom-assets/kenney/isometric/tableCoffeeSquare_SE.png', 60, 60),
        ('Kenney Table Cross', 'Kenney isometric miniroom item', 400, 'kenney_isometric_table_cross_se', '/miniroom-assets/kenney/isometric/tableCross_SE.png', 99, 93),
        ('Kenney Table Cross Cloth', 'Kenney isometric miniroom item', 400, 'kenney_isometric_table_cross_cloth_se', '/miniroom-assets/kenney/isometric/tableCrossCloth_SE.png', 99, 93),
        ('Kenney Table Glass', 'Kenney isometric miniroom item', 400, 'kenney_isometric_table_glass_se', '/miniroom-assets/kenney/isometric/tableGlass_SE.png', 98, 93),
        ('Kenney Table Round', 'Kenney isometric miniroom item', 400, 'kenney_isometric_table_round_se', '/miniroom-assets/kenney/isometric/tableRound_SE.png', 83, 69),
        ('Kenney Television Antenna', 'Kenney isometric miniroom item', 400, 'kenney_isometric_television_antenna_se', '/miniroom-assets/kenney/isometric/televisionAntenna_SE.png', 22, 18),
        ('Kenney Television Modern', 'Kenney isometric miniroom item', 400, 'kenney_isometric_television_modern_se', '/miniroom-assets/kenney/isometric/televisionModern_SE.png', 54, 68),
        ('Kenney Television Vintage', 'Kenney isometric miniroom item', 400, 'kenney_isometric_television_vintage_se', '/miniroom-assets/kenney/isometric/televisionVintage_SE.png', 46, 53),
        ('Kenney Toilet', 'Kenney isometric miniroom item', 400, 'kenney_isometric_toilet_se', '/miniroom-assets/kenney/isometric/toilet_SE.png', 54, 70),
        ('Kenney Trashcan', 'Kenney isometric miniroom item', 400, 'kenney_isometric_trashcan_se', '/miniroom-assets/kenney/isometric/trashcan_SE.png', 25, 46),
        ('Kenney Wall', 'Kenney isometric miniroom item', 400, 'kenney_isometric_wall_se', '/miniroom-assets/kenney/isometric/wall_SE.png', 80, 153),
        ('Kenney Wall Corner', 'Kenney isometric miniroom item', 400, 'kenney_isometric_wall_corner_se', '/miniroom-assets/kenney/isometric/wallCorner_SE.png', 38, 156),
        ('Kenney Wall Corner Rond', 'Kenney isometric miniroom item', 400, 'kenney_isometric_wall_corner_rond_se', '/miniroom-assets/kenney/isometric/wallCornerRond_SE.png', 42, 156),
        ('Kenney Wall Doorway', 'Kenney isometric miniroom item', 400, 'kenney_isometric_wall_doorway_se', '/miniroom-assets/kenney/isometric/wallDoorway_SE.png', 80, 153),
        ('Kenney Wall Doorway Wide', 'Kenney isometric miniroom item', 400, 'kenney_isometric_wall_doorway_wide_se', '/miniroom-assets/kenney/isometric/wallDoorwayWide_SE.png', 80, 153),
        ('Kenney Wall Half', 'Kenney isometric miniroom item', 400, 'kenney_isometric_wall_half_se', '/miniroom-assets/kenney/isometric/wallHalf_SE.png', 42, 127),
        ('Kenney Wall Window', 'Kenney isometric miniroom item', 400, 'kenney_isometric_wall_window_se', '/miniroom-assets/kenney/isometric/wallWindow_SE.png', 80, 153),
        ('Kenney Wall Window Slide', 'Kenney isometric miniroom item', 400, 'kenney_isometric_wall_window_slide_se', '/miniroom-assets/kenney/isometric/wallWindowSlide_SE.png', 80, 153),
        ('Kenney Washer', 'Kenney isometric miniroom item', 400, 'kenney_isometric_washer_se', '/miniroom-assets/kenney/isometric/washer_SE.png', 56, 74),
        ('Kenney Washer Dryer Stacked', 'Kenney isometric miniroom item', 400, 'kenney_isometric_washer_dryer_stacked_se', '/miniroom-assets/kenney/isometric/washerDryerStacked_SE.png', 56, 109)
) AS seed(name, description, price, asset_key, asset_url, asset_width, asset_height)
WHERE u.email = 'miniroom-dev@example.com'
  AND NOT EXISTS (
      SELECT 1
      FROM item i
      WHERE i.asset_key = seed.asset_key
  );


-- merged from V21__seed_room_background_shop_items.sql
UPDATE item
SET name = 'Room Blue Background',
    description = 'Purchasable miniroom background',
    price = 500,
    status = 'ACTIVE',
    asset_key = 'room_blue',
    asset_url = '/miniroom-assets/rooms/room-blue.svg',
    asset_width = 750,
    asset_height = 606,
    placement_type = 'BACKGROUND',
    updated_at = NOW()
WHERE category = 'BACKGROUND'
  AND asset_key = 'room_blue';

INSERT INTO item (
    category,
    name,
    description,
    price,
    status,
    sales_count,
    creator_id,
    asset_key,
    asset_url,
    asset_width,
    asset_height,
    placement_type,
    created_at,
    updated_at
)
SELECT
    'BACKGROUND',
    seed.name,
    seed.description,
    seed.price,
    'ACTIVE',
    0,
    u.user_id,
    seed.asset_key,
    seed.asset_url,
    750,
    606,
    'BACKGROUND',
    NOW(),
    NOW()
FROM users u
CROSS JOIN (
    VALUES
        ('Room Blue Background', 'Purchasable miniroom background', 500, 'room_blue', '/miniroom-assets/rooms/room-blue.svg'),
        ('Room Dark Background', 'Purchasable miniroom background', 500, 'room_dark', '/miniroom-assets/rooms/room-dark.svg'),
        ('Room Green Background', 'Purchasable miniroom background', 500, 'room_green', '/miniroom-assets/rooms/room-green.svg'),
        ('Room Lab Background', 'Purchasable miniroom background', 500, 'room_lab', '/miniroom-assets/rooms/room-lab.svg'),
        ('Room Pink Background', 'Purchasable miniroom background', 500, 'room_pink', '/miniroom-assets/rooms/room-pink.svg')
) AS seed(name, description, price, asset_key, asset_url)
WHERE u.email = 'miniroom-dev@example.com'
  AND NOT EXISTS (
      SELECT 1
      FROM item i
      WHERE i.asset_key = seed.asset_key
  );


-- merged from V24__localize_miniroom_item_names.sql
UPDATE item
SET name = localized.name,
    description = localized.description,
    updated_at = NOW()
FROM (
    VALUES
        ('sofa_blue', '블루 소파', '미니룸에 배치할 수 있는 소파 아이템'),
        ('desk_se', '원목 책상', '미니룸에 배치할 수 있는 책상 아이템'),
        ('floor_lamp_orange', '오렌지 스탠드', '미니룸에 배치할 수 있는 조명 아이템'),
        ('room_blue', '블루 룸 배경', '구매 가능한 미니룸 배경'),
        ('room_dark', '다크 룸 배경', '구매 가능한 미니룸 배경'),
        ('room_green', '그린 룸 배경', '구매 가능한 미니룸 배경'),
        ('room_lab', '연구실 룸 배경', '구매 가능한 미니룸 배경'),
        ('room_pink', '핑크 룸 배경', '구매 가능한 미니룸 배경'),
        ('grafxkid_avatar_01', '기본 미니미 01', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_02', '기본 미니미 02', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_03', '기본 미니미 03', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_04', '기본 미니미 04', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_05', '기본 미니미 05', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_06', '기본 미니미 06', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_07', '기본 미니미 07', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_08', '기본 미니미 08', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_09', '기본 미니미 09', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_10', '기본 미니미 10', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_11', '기본 미니미 11', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_12', '기본 미니미 12', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_13', '기본 미니미 13', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_14', '기본 미니미 14', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_15', '기본 미니미 15', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_16', '기본 미니미 16', '구매 가능한 픽셀 아바타'),
        ('grafxkid_avatar_17', '기본 미니미 17', '구매 가능한 픽셀 아바타')
) AS localized(asset_key, name, description)
WHERE item.asset_key = localized.asset_key;
UPDATE item
SET name = localized.name,
    description = localized.description,
    updated_at = NOW()
FROM (
    VALUES
        ('kenney_isometric_bathroom_cabinet_se', '욕실 수납장', '미니룸 욕실 분위기를 완성하는 수납장'),
        ('kenney_isometric_bathroom_mirror_se', '욕실 거울', '벽면에 어울리는 깔끔한 욕실 거울'),
        ('kenney_isometric_bathroom_sink_se', '세면대', '작은 욕실 공간에 놓기 좋은 세면대'),
        ('kenney_isometric_bathtub_se', '클래식 욕조', '편안한 욕실 분위기의 욕조 아이템'),
        ('kenney_isometric_bear_se', '작은 곰인형', '방 한쪽에 두기 좋은 포근한 곰인형'),
        ('kenney_isometric_bed_bunk_se', '2층 침대', '아늑한 침실을 만드는 2층 침대'),
        ('kenney_isometric_bed_double_se', '더블 침대', '넓고 포근한 침실용 더블 침대'),
        ('kenney_isometric_bed_single_se', '싱글 침대', '혼자 쓰기 좋은 기본 침대'),
        ('kenney_isometric_bench_se', '우드 벤치', '심플하게 배치하기 좋은 나무 벤치'),
        ('kenney_isometric_bench_cushion_se', '쿠션 벤치', '포근한 쿠션이 올라간 벤치'),
        ('kenney_isometric_bench_cushion_low_se', '낮은 쿠션 벤치', '작은 공간에 잘 맞는 낮은 벤치'),
        ('kenney_isometric_bookcase_closed_se', '닫힌 책장', '차분한 서재 느낌의 닫힌 책장'),
        ('kenney_isometric_bookcase_closed_doors_se', '도어 책장', '문이 달린 정돈된 책장'),
        ('kenney_isometric_bookcase_closed_wide_se', '와이드 수납책장', '넓은 벽면을 채우는 큰 책장'),
        ('kenney_isometric_bookcase_open_se', '오픈 책장', '책과 소품을 보여주기 좋은 책장'),
        ('kenney_isometric_bookcase_open_low_se', '낮은 오픈 책장', '창가 아래에 두기 좋은 낮은 책장'),
        ('kenney_isometric_books_se', '쌓인 책', '책상이나 바닥에 놓기 좋은 책 더미'),
        ('kenney_isometric_cabinet_bed_se', '침대 협탁', '침대 옆에 놓는 작은 협탁'),
        ('kenney_isometric_cabinet_bed_drawer_se', '서랍 협탁', '수납 서랍이 있는 침대 협탁'),
        ('kenney_isometric_cabinet_bed_drawer_table_se', '미니 사이드 테이블', '침대 옆 소품을 올려두는 테이블'),
        ('kenney_isometric_cabinet_television_se', '모던 TV장', 'TV와 함께 놓기 좋은 거실장'),
        ('kenney_isometric_cabinet_television_doors_se', '도어 TV장', '문이 달린 깔끔한 TV 수납장'),
        ('kenney_isometric_cardboard_box_closed_se', '닫힌 택배 상자', '방 안에 자연스럽게 놓이는 작은 상자'),
        ('kenney_isometric_cardboard_box_open_se', '열린 택배 상자', '짐 정리 중인 느낌의 열린 상자'),
        ('kenney_isometric_ceiling_fan_se', '천장 선풍기', '방에 시원한 포인트를 더하는 천장 팬'),
        ('kenney_isometric_chair_se', '기본 의자', '어디에나 잘 어울리는 심플 의자'),
        ('kenney_isometric_chair_cushion_se', '쿠션 의자', '폭신한 쿠션이 있는 의자'),
        ('kenney_isometric_chair_desk_se', '책상 의자', '책상과 함께 쓰기 좋은 의자'),
        ('kenney_isometric_chair_rounded_se', '라운드 의자', '둥근 등받이가 귀여운 의자'),
        ('kenney_isometric_coat_rack_se', '벽걸이 옷걸이', '벽면에 배치하는 작은 옷걸이'),
        ('kenney_isometric_coat_rack_standing_se', '스탠딩 옷걸이', '입구나 침실에 세워두는 옷걸이'),
        ('kenney_isometric_computer_keyboard_se', '컴퓨터 키보드', '책상 위에 올리는 키보드'),
        ('kenney_isometric_computer_mouse_se', '컴퓨터 마우스', '키보드 옆에 두는 작은 마우스'),
        ('kenney_isometric_computer_screen_se', '컴퓨터 모니터', '작업 공간을 꾸미는 모니터'),
        ('kenney_isometric_desk_se', '원목 책상', '공부방이나 작업실에 어울리는 책상'),
        ('kenney_isometric_desk_corner_se', '코너 책상', '방 모서리에 딱 맞는 넓은 책상'),
        ('kenney_isometric_doorway_se', '기본 출입문', '벽면에 배치하는 출입문'),
        ('kenney_isometric_doorway_front_se', '정면 출입문', '정면을 바라보는 문 아이템'),
        ('kenney_isometric_doorway_open_se', '열린 출입문', '공간에 깊이를 주는 열린 문'),
        ('kenney_isometric_dryer_se', '건조기', '세탁 공간에 어울리는 건조기'),
        ('kenney_isometric_floor_corner_se', '코너 바닥', '방 모서리를 만드는 바닥 타일'),
        ('kenney_isometric_floor_corner_round_se', '라운드 코너 바닥', '둥근 모서리 형태의 바닥 타일'),
        ('kenney_isometric_floor_full_se', '풀 사이즈 바닥', '방의 중심을 채우는 큰 바닥 타일'),
        ('kenney_isometric_floor_half_se', '하프 바닥', '부분 배치에 좋은 작은 바닥 타일'),
        ('kenney_isometric_kitchen_bar_se', '주방 바 테이블', '홈 카페 느낌을 주는 바 테이블'),
        ('kenney_isometric_kitchen_bar_end_se', '주방 바 끝장', '바 테이블 끝에 붙이는 마감장'),
        ('kenney_isometric_kitchen_blender_se', '미니 블렌더', '주방 조리대에 올리는 작은 블렌더'),
        ('kenney_isometric_kitchen_cabinet_se', '주방 하부장', '기본 주방을 만드는 하부 수납장'),
        ('kenney_isometric_kitchen_cabinet_corner_inner_se', '주방 안쪽 코너장', 'ㄱ자 주방에 맞는 안쪽 코너장'),
        ('kenney_isometric_kitchen_cabinet_corner_round_se', '라운드 코너장', '둥근 모서리의 주방 코너장'),
        ('kenney_isometric_kitchen_cabinet_drawer_1_se', '넓은 서랍장', '주방 수납을 늘려주는 넓은 서랍장'),
        ('kenney_isometric_kitchen_cabinet_drawer_se', '주방 서랍장', '조리도구를 보관하는 서랍장'),
        ('kenney_isometric_kitchen_cabinet_upper_se', '주방 상부장', '벽면에 설치하는 기본 상부장'),
        ('kenney_isometric_kitchen_cabinet_upper_corner_se', '코너 상부장', '주방 모서리에 맞는 상부장'),
        ('kenney_isometric_kitchen_cabinet_upper_double_se', '더블 상부장', '넉넉한 수납을 위한 이중 상부장'),
        ('kenney_isometric_kitchen_cabinet_upper_low_se', '낮은 상부장', '작은 벽면에 놓기 좋은 낮은 상부장'),
        ('kenney_isometric_kitchen_coffee_machine_se', '커피 머신', '홈 카페 감성을 더하는 커피 머신'),
        ('kenney_isometric_kitchen_fridge_se', '기본 냉장고', '주방에 꼭 필요한 냉장고'),
        ('kenney_isometric_kitchen_fridge_built_in_se', '빌트인 냉장고', '깔끔하게 들어맞는 빌트인 냉장고'),
        ('kenney_isometric_kitchen_fridge_small_se', '미니 냉장고', '작은 공간에 놓기 좋은 냉장고'),
        ('kenney_isometric_kitchen_microwave_se', '전자레인지', '주방 선반에 올리는 전자레인지'),
        ('kenney_isometric_kitchen_sink_se', '주방 싱크대', '조리 공간의 중심이 되는 싱크대'),
        ('kenney_isometric_kitchen_stove_se', '가스레인지', '따뜻한 주방을 만드는 조리대'),
        ('kenney_isometric_kitchen_stove_electric_se', '전기레인지', '모던한 주방용 전기레인지'),
        ('kenney_isometric_lamp_round_floor_se', '라운드 장스탠드', '둥근 갓이 있는 바닥 스탠드'),
        ('kenney_isometric_lamp_round_table_se', '라운드 단스탠드', '협탁 위에 어울리는 작은 조명'),
        ('kenney_isometric_lamp_square_ceiling_se', '사각 천장등', '천장에 다는 깔끔한 조명'),
        ('kenney_isometric_lamp_square_floor_se', '사각 장스탠드', '각진 갓이 있는 바닥 스탠드'),
        ('kenney_isometric_lamp_square_table_se', '사각 단스탠드', '책상이나 협탁 위에 놓는 조명'),
        ('kenney_isometric_laptop_se', '노트북', '작업 공간에 올려두는 노트북'),
        ('kenney_isometric_lounge_chair_se', '라운지 의자', '편하게 앉기 좋은 1인 의자'),
        ('kenney_isometric_lounge_chair_relax_se', '리클라이너 의자', '느긋한 분위기의 휴식 의자'),
        ('kenney_isometric_lounge_sofa_se', '라운지 소파', '거실에 어울리는 기본 소파'),
        ('kenney_isometric_lounge_sofa_corner_se', '코너 소파', '방 모서리를 채우는 ㄱ자 소파'),
        ('kenney_isometric_lounge_sofa_long_se', '롱 소파', '길게 누울 수 있는 넓은 소파'),
        ('kenney_isometric_lounge_sofa_ottoman_se', '소파 오토만', '소파 앞에 두는 발받침 스툴'),
        ('kenney_isometric_paneling_se', '우드 패널', '벽면에 포인트를 주는 나무 패널'),
        ('kenney_isometric_pillow_se', '작은 베개', '침대나 소파 위에 놓는 베개'),
        ('kenney_isometric_pillow_long_se', '긴 베개', '침대 위에 어울리는 롱 쿠션'),
        ('kenney_isometric_plant_small1_se', '새싹 화분', '작은 초록 포인트 화분'),
        ('kenney_isometric_plant_small2_se', '둥근잎 화분', '방 안을 산뜻하게 하는 작은 화분'),
        ('kenney_isometric_plant_small3_se', '미니 선인장', '책상 위에 놓기 좋은 작은 식물'),
        ('kenney_isometric_potted_plant_se', '키 큰 화분', '공간을 싱그럽게 채우는 큰 화분'),
        ('kenney_isometric_radio_se', '레트로 라디오', '옛 감성이 나는 작은 라디오'),
        ('kenney_isometric_rug_rectangle_se', '직사각 러그', '방 중앙에 깔기 좋은 넓은 러그'),
        ('kenney_isometric_rug_round_se', '라운드 러그', '둥근 형태의 포인트 러그'),
        ('kenney_isometric_rug_rounded_se', '둥근 모서리 러그', '부드러운 인상의 사각 러그'),
        ('kenney_isometric_rug_square_se', '스퀘어 러그', '작은 공간에 맞는 정사각 러그'),
        ('kenney_isometric_shower_se', '샤워 부스', '욕실에 배치하는 샤워 공간'),
        ('kenney_isometric_side_table_se', '사이드 테이블', '소파 옆에 두기 좋은 작은 테이블'),
        ('kenney_isometric_side_table_drawers_se', '서랍 사이드 테이블', '수납이 가능한 작은 테이블'),
        ('kenney_isometric_speaker_se', '톨 스피커', '음악방 느낌을 주는 큰 스피커'),
        ('kenney_isometric_speaker_small_se', '미니 스피커', '책상 위에 올리는 작은 스피커'),
        ('kenney_isometric_stool_bar_se', '바 스툴', '바 테이블과 어울리는 높은 의자'),
        ('kenney_isometric_stool_bar_square_se', '사각 바 스툴', '각진 디자인의 높은 스툴'),
        ('kenney_isometric_table_se', '기본 테이블', '다용도로 쓰기 좋은 테이블'),
        ('kenney_isometric_table_cloth_se', '식탁보 테이블', '식탁보가 덮인 따뜻한 테이블'),
        ('kenney_isometric_table_coffee_se', '커피 테이블', '소파 앞에 두는 낮은 테이블'),
        ('kenney_isometric_table_coffee_glass_se', '유리 커피 테이블', '투명한 상판의 낮은 테이블'),
        ('kenney_isometric_table_coffee_glass_square_se', '사각 유리 테이블', '작고 깔끔한 유리 테이블'),
        ('kenney_isometric_table_coffee_square_se', '사각 커피 테이블', '소파 앞에 놓기 좋은 사각 테이블'),
        ('kenney_isometric_table_cross_se', '크로스 테이블', '다리 모양이 돋보이는 테이블'),
        ('kenney_isometric_table_cross_cloth_se', '크로스 식탁보 테이블', '식탁보가 덮인 크로스 테이블'),
        ('kenney_isometric_table_glass_se', '유리 테이블', '모던한 느낌의 유리 테이블'),
        ('kenney_isometric_table_round_se', '원형 테이블', '둥근 상판의 작은 테이블'),
        ('kenney_isometric_television_antenna_se', '안테나 TV', '레트로한 분위기의 안테나 TV'),
        ('kenney_isometric_television_modern_se', '모던 TV', '깔끔한 거실용 TV'),
        ('kenney_isometric_television_vintage_se', '브라운관 TV', '추억 감성이 있는 빈티지 TV'),
        ('kenney_isometric_toilet_se', '변기', '욕실 구성에 필요한 변기'),
        ('kenney_isometric_trashcan_se', '휴지통', '방 구석에 놓기 좋은 작은 휴지통'),
        ('kenney_isometric_wall_se', '기본 벽면', '미니룸 공간을 나누는 벽면'),
        ('kenney_isometric_wall_corner_se', '코너 벽면', '방 모서리를 만드는 벽면'),
        ('kenney_isometric_wall_corner_rond_se', '라운드 코너 벽면', '둥근 모서리 형태의 벽면'),
        ('kenney_isometric_wall_doorway_se', '문틀 벽면', '출입구가 있는 벽면'),
        ('kenney_isometric_wall_doorway_wide_se', '넓은 문틀 벽면', '큰 출입구가 있는 벽면'),
        ('kenney_isometric_wall_half_se', '낮은 벽면', '공간을 가볍게 나누는 낮은 벽'),
        ('kenney_isometric_wall_window_se', '창문 벽면', '창문이 있는 밝은 벽면'),
        ('kenney_isometric_wall_window_slide_se', '슬라이드 창문 벽면', '미닫이 창문이 있는 벽면'),
        ('kenney_isometric_washer_se', '세탁기', '세탁 공간에 놓는 기본 세탁기'),
        ('kenney_isometric_washer_dryer_stacked_se', '타워 세탁건조기', '세탁기와 건조기가 쌓인 타워형 가전')
) AS localized(asset_key, name, description)
WHERE item.asset_key = localized.asset_key;
